### ISSUE TITLE
segfault on mail parsing

### ISSUE THREAD

**Issue by avoine** [gauteh/abunchoftags#1]
I know the software is experimental but I wanted let you know that I got a segfault by doing:

keywsync -m mail/ -k -p -a -q "*"

The trace is:

<pre>
open("mail/Sent/cur/1451701521_7.14042.flocon,U=284,FMD5=7f8c0283f16925caed8e632086b81b9c:2,S", O_RDONLY) = 8
lseek(8, 0, SEEK_CUR)                   = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=5063, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f17c932b000
lseek(8, 0, SEEK_SET)                   = 0
read(8, "Date: Fri, 13 Aug 2010 15:10:18 "..., 4096) = 4096
open("/gnu/store/rwvf6xqgsyb8bmpi7rwk9fildnwvzrv5-tzdata-2015c/share/zoneinfo/America/New_York", O_RDONLY|O_CLOEXEC) =
 9                                                                                                                   
fstat(9, {st_mode=S_IFREG|0444, st_size=3545, ...}) = 0
fstat(9, {st_mode=S_IFREG|0444, st_size=3545, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f17c932a000
read(9, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 3545
lseek(9, -2261, SEEK_CUR)               = 1284
read(9, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 2261
close(9)                                = 0
munmap(0x7f17c932a000, 4096)            = 0
open("/gnu/store/qv7bk62c22ms9i11dhfl71hnivyc82k2-glibc-2.22/lib/gconv/ISO8859-1.so", O_RDONLY|O_CLOEXEC) = 9
read(9, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\5\0\0\0\0\0\0"..., 832) = 832
fstat(9, {st_mode=S_IFREG|0555, st_size=12600, ...}) = 0
mmap(NULL, 2105432, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 9, 0) = 0x7f17c4bd1000
mprotect(0x7f17c4bd3000, 2093056, PROT_NONE) = 0
mmap(0x7f17c4dd2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 9, 0x1000) = 0x7f17c4dd2000
close(9)                                = 0
mprotect(0x7f17c4dd2000, 4096, PROT_READ) = 0
lseek(8, 4096, SEEK_SET)                = 4096
read(8, " une id=E9e comment cela a  p=FB"..., 4096) = 967
read(8, "", 4096)                       = 0
lseek(8, 4096, SEEK_SET)                = 4096
read(8, " une id=E9e comment cela a  p=FB"..., 967) = 967
read(8, "", 4096)                       = 0
close(8)                                = 0
munmap(0x7f17c932b000, 4096)            = 0
stat("mail/Sent/cur/1451701521_7.14042.flocon,U=284,FMD5=7f8c0283f16925caed8e632086b81b9c:2,S", {st_mode=S_IFREG|0644,
 st_size=5063, ...}) = 0                                                                                             
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x48} ---
+++ killed by SIGSEGV +++
Segmentation fault
</pre>

**Comment by gauteh** [comment]
Hi,

does this happen consistently? Could you try to run it with both -v and
--more-verbose. Also, it seems like the error occurs on a specific file.
does it exist? It seems like there might be an issue with an header or
some encoding. It would be useful to have a copy of the message if you
could strip out any private/sensitive stuff.
- gaute

**Comment by avoine** [comment]
That must be the encoding it use ISO-8859-1. I'll check if I can convert it to utf-8.

<pre>
avoine@flocon ~$ cat "mail/Sent/cur/1451701521_8.14042.flocon,U=285,FMD5=7f8c0283f16925caed8e632086b81b9c:2,S" 
Date: Tue, 30 Nov 2010 14:23:10 -0500
From: Patrick =?ISO-8859-1?Q?H=E9tu?= <patrick@koumbit.org>
Subject: suivi support Moodle
X-Mailer: Sylpheed 3.1.0beta2 (GTK+ 2.23.2; i686-pc-linux-gnu)
Mime-Version: 1.0
X-Keywords: 
Content-Type: text/plain; charset=ISO-8859-1
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
[...]
Bonne fin de journ=E9e
Patrick
</pre>

**Comment by avoine** [comment]
After more tests it turn out that all emails encoded with ISO-8859-1 or UTF-8 are causing a segfault.

**Comment by gauteh** [comment]
Patrick writes on January 2, 2016 17:49:

> After more test it turn out that all emails encoded with ISO-8859-1 or UTF-8 are causing a segfault.

With inline encoding like:

```
  Patrick =?ISO-8859-1?Q?H=E9tu?= 
```

what linux are you running and what version of gmime are you using?

**Comment by avoine** [comment]
I'm using GuixSD (https://www.gnu.org/software/guix/) with these versions:

gmime 2.6.20
notmuch 0.20.2 
glibmm 2.46.1
pkg-config 0.28
boost 1.58.0
scons 2.3.4

**Comment by gauteh** [comment]
Patrick writes on January 2, 2016 19:06:

> I'm using GuixSD (https://www.gnu.org/software/guix/) with these versions:
> 
> gmime 2.6.20
> notmuch 0.20.2 
> glibmm 2.46.1

I have a newer version of glibmm (2.46.3) on Arch Linux, but gmime is
the same. I am not able to reproduce the error using the sample you
sent, perhaps if you tar+gzipped it so that the encoding is preserved it
works better.

Also, if you have the chance of running it through gdb (with debug
symbols) so that I could get a backtrace of the error and pinpoint the
code-line that would be very useful. Handling the error from gmime (or
the conversion to ustring) should be possible.

Regards, Gaute

**Comment by gauteh** [comment]
I set up a test system: I added your sample file to
test/mail/test_mail/weird-enc-header.eml and it is being tested in
test/test_kw_to_tag.sh.

You can run the tests with: `scons test`, and clean them out with `scons
clean_test`. Can you check if this test is able to reproduce the issue?

(P.S: I assumed it was ok to include your sample email there since you
posted it in this issue).

Regards, Gaute

**Comment by avoine** [comment]
Found it! I ran gdb and to my surprise everything was working. Then I realized that I was using an absolute path to the database like this:

keywsync -m ~/mail/ -k -p -a -q "*"

instead of:

keywsync -m mail/ -k -p -a -q "*"

So I guess that must be a bug in the way abunchoftags joins the paths in the database with the one provided in the command line.

**Comment by gauteh** [comment]
Weird! I pushed a change where the absolute path is used, does that fix it?

**Comment by avoine** [comment]
yes 690fe41 fix it.
