### ISSUE TITLE
Meaning of words in the README

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [gauteh/abunchoftags#2]
What do you mean by

> Note: The query needs to filter messages so that only the messages of the GMail maildir are tested.

in the README? Does that mean that it only works with GMail? What I want to do is the following:

> ASTROID A <=> NOTMUCH A <=abunchoftags=> MAILDIR A <=offlineimap=> REMOTE (not necessarily GMail) <=offlineimap=> MAILDIR B <=abunchoftags=> NOTMUCH B <=> ASTROID B.

where A and B are different computers. Would it work?

**Comment by gauteh** [comment]
Aurélien Ooms writes on January 14, 2016 16:06:

> What do you mean by
> 
> > Note: The query needs to filter messages so that only the messages of the GMail maildir are tested.
> 
> in the README? Does that mean that it only works with GMail? What I want to do is the following:
> 
> > ASTROID A <=> NOTMUCH A <=abunchoftags=> MAILDIR A <=offlineimap=> REMOTE (not necessarily GMail) <=offlineimap=> MAILDIR B <=abunchoftags=> NOTMUCH B <=> ASTROID B.
> 
> where A and B are different computers. Would it work?

It would work for GMail. I don't know if other IMAP servers would like
it. I think muchsync might be able to do that.
- gaute

**Comment by make-github-pseudonymous-again** [comment]
> I think muchsync might be able to do that.

Thanks. I'll see what I can do with muchsync.
