### ISSUE TITLE
AUR package not online?

### ISSUE THREAD

**Issue by pinpox** [gauteh/abunchoftags#3]
Hi, 

I can't find the AUR package with the search. 
Is it not online, if so is that intentional?

Regards

**Comment by gauteh** [comment]
binaryplease writes on March 10, 2016 11:39:

> I can't find the AUR package with the search. 
> Is it not online, if so is that intentional?

I don't think I published it yet. I'll see if I can do it today.

**Comment by gauteh** [comment]
Gaute Hope writes on March 10, 2016 12:04:

> binaryplease writes on March 10, 2016 11:39:
> 
> > I can't find the AUR package with the search. 
> > Is it not online, if so is that intentional?
> 
> I don't think I published it yet. I'll see if I can do it today.

Added.
